# Numpy

NumPy es el paquete fundamental para la computación científica en Python. Es una librería de Python que proporciona un objeto array multidimensional,  y una serie de rutinas para operaciones rápidas sobre arrays, incluyendo operaciones matemáticas, lógicas, manipulación de formas, ordenación, selección, álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.

Existen varias diferencias importantes entre los arrays de NumPy y las listas estándar de Python:

- Los arrays de NumPy tienen un tamaño fijo en el momento de su creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Si se cambia el tamaño de una matriz NumPy, se creará un nuevo array y se borrará el original.

- Los elementos de un array de NumPy deben ser todos del mismo tipo de datos y, por tanto, tendrán el mismo tamaño en memoria.

- Los arrays de NumPy facilitan las operaciones matemáticas avanzadas y otros tipos de operaciones con grandes cantidades de datos. Normalmente, estas operaciones se ejecutan de forma más eficiente y con menos código que con las listas incorporadas en Python.

- Una bateria creciente de paquetes científicos y matemáticos basados en Python utilizan arrays de NumPy; aunque normalmente admiten la entrada de listas de Python, convierten dicha entrada en arrays de NumPy antes de procesarla, y a menudo dan como salida arrays de NumPy. En otras palabras, para utilizar eficientemente gran parte del software científico/matemático actual basado en Python, no basta con saber utilizar listas, sino que también hay que saber utilizar los arrays de NumPy.

- Un array puede ser de una dimensión (como una lista), de dos dimensiones (como una matriz) o incluso de más dimensiones.


![arrays de distintas dimensiones](https://www.pythontutorial.net/wp-content/uploads/2022/08/what-is-numpy-1024x572.png)

### Creación de arrays

In [1]:
import numpy as np


In [2]:
# ARRAYS: FORMAS DE CREACION ---

print(f"Creacion de array con lista (se especifican los valores): {np.array([1,2,3])}")

print(f"Creacion de array con arange (valores spaciados en un intervalo): {np.arange(start = 1, stop = 10, step = 1)}")

print(f"Creacion de array con linspace (valores espaciados en un intervalo): {np.linspace(start = 1, stop = 10, num = 10)}")

print(f"Creacion de array con zeros (todos los valores son 0): {np.zeros(shape = 5, dtype=int)}")

print(f"Creacion de array con ones (todos los valores son 1): {np.ones(5, dtype=int)}")



Creacion de array con lista (se especifican los valores): [1 2 3]
Creacion de array con arange (valores spaciados en un intervalo): [1 2 3 4 5 6 7 8 9]
Creacion de array con linspace (valores espaciados en un intervalo): [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Creacion de array con zeros (todos los valores son 0): [0 0 0 0 0]
Creacion de array con ones (todos los valores son 1): [1 1 1 1 1]


In [3]:
# MATRICES: ---
lista_a = [1, 2]
lista_b = [4, 5]

matriz_a_con_listas = [lista_a, lista_a]
matriz_b_con_listas = [lista_b, lista_b]

matriz_a_con_arrays = np.array([lista_a, lista_a])
matriz_b_con_arrays = np.array([lista_b, lista_b])

print(f"Así se vería la matriz_a en numpy: \n {matriz_a_con_listas}")
print(f"Así se vería la matriz_b en numpy: \n {matriz_b_con_listas}")

print(f"Así se vería la matriz_a en numpy: \n {matriz_a_con_arrays}")
print(f"Así se vería la matriz_b en numpy: \n {matriz_b_con_arrays}")

Así se vería la matriz_a en numpy: 
 [[1, 2], [1, 2]]
Así se vería la matriz_b en numpy: 
 [[4, 5], [4, 5]]
Así se vería la matriz_a en numpy: 
 [[1 2]
 [1 2]]
Así se vería la matriz_b en numpy: 
 [[4 5]
 [4 5]]


### Operaciones con arrays

In [4]:
# ARRAYS: OPERACION SUMA ----
lista_a = [1, 2]
lista_b = [4, 5]

array_a = np.array(lista_a)
array_b = np.array(lista_b)

print(f"Sumamos las listas: {lista_a + lista_b}")
print(f"Sumamos los arrays: {array_a + array_b}")

# Si quiero que las listas se sumen como los arrays
# print(f"Sumando las listas como si fuesen arrays: {[a + b for a, b in zip(lista_a, lista_b)]}")

# Si quiero que los arrays se sumen como las listas
# print(f"Si queremos concatenar los arrays como las listas: {np.concatenate((array_a, array_b))}")

Sumamos las listas: [1, 2, 4, 5]
Sumamos los arrays: [5 7]


In [5]:
# ARRAYS: OPERACION MULTIPLICACION ---


print(f"Multiplicamos las listas: {lista_a * lista_b}")  #! Esto dara error ya que no se pueden multiplicar listas por defecto

print(f"Multiplicamos los arrays: {array_a * array_b}")
print(f"Multiplicamos las listas como si fuesen arrays: {[a * b for a, b in zip(lista_a, lista_b)]}")


TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
# MATRICES: OPERACION MULTIPLICACION ---

resultado_con_arrays = matriz_a_con_arrays * matriz_b_con_arrays
print(f"Así se vería la multiplicacion usando arrays: \n {resultado_con_arrays}")


resultado_con_listas = [[0 for _ in range(len(matriz_b_con_listas[0]))] for _ in range(len(matriz_a_con_listas))]
for i in range(len(matriz_a_con_listas)):  # Filas de matriz_a
  for j in range(len(matriz_b_con_listas[0])):
    resultado_con_listas[i][j] = matriz_a_con_listas[i][j] * matriz_b_con_listas[i][j]

print(f"Así se vería la multiplicacion usando listas: \n {resultado_con_listas}")



Así se vería la multiplicacion usando arrays: 
 [[ 4 10]
 [ 4 10]]
Así se vería la multiplicacion usando listas: 
 [[4, 10], [4, 10]]


In [7]:
# MATRICES: OPERACION MULTIPLICACION DOT ---

print(f"Multiplicamos matriz_a_con_arrays con matriz_b_con_arrays:\n {np.dot(matriz_a_con_arrays, matriz_b_con_arrays)}")
print(f"Multiplicamos matriz_b_con_arrays con matriz_a_con_arrays:\n {np.dot(matriz_b_con_arrays, matriz_a_con_arrays)}")



Multiplicamos matriz_a_con_arrays con matriz_b_con_arrays:
 [[12 15]
 [12 15]]
Multiplicamos matriz_b_con_arrays con matriz_a_con_arrays:
 [[ 9 18]
 [ 9 18]]


In [8]:
# MATRICES: OPERACIONES GENERICAS ---

print(f"Sumamos 10 a todos los elementos de la matriz:\n {matriz_a_con_arrays + 10}")
print(f"Multiplicamos por 10 todos los elementos de la matriz:\n {matriz_a_con_arrays * 10}")
print(f"Calculamos la raiz cuadrada de todos los elementos de la matriz:\n {np.sqrt(matriz_a_con_arrays)}")
print(f"Calculamos el logaritmo de todos los elementos de la matriz:\n {np.log(matriz_a_con_arrays)}")
print(f"Calculamos el seno de todos los elementos de la matriz:\n {np.sin(matriz_a_con_arrays)}")


Sumamos 10 a todos los elementos de la matriz:
 [[11 12]
 [11 12]]
Multiplicamos por 10 todos los elementos de la matriz:
 [[10 20]
 [10 20]]
Calculamos la raiz cuadrada de todos los elementos de la matriz:
 [[1.         1.41421356]
 [1.         1.41421356]]
Calculamos el logaritmo de todos los elementos de la matriz:
 [[0.         0.69314718]
 [0.         0.69314718]]
Calculamos el seno de todos los elementos de la matriz:
 [[0.84147098 0.90929743]
 [0.84147098 0.90929743]]


### Propiedades

In [9]:
# ARRAYS: PROPIEDADES ---

array_a = np.array([[1, 2, 3, 4], [2,3,4,np.nan]])

print(f"array_a:\n {array_a} \n")

print("Size:", array_a.size)

# check len of the array
print("len:", len(array_a))

# check shape of the array
print("Shape:", array_a.shape)

print(f"Matriz traspuesta:\n {array_a.T}")

print(f"Shape de la matriz traspuesta: {array_a.T.shape}")

print(f"Cambiamos las dimensiones a (1,8): {array_a.reshape(1, 8)}")

# check dtype of the array elements
print("Datatype:", array_a.dtype)

# change the dtype to 'float64'
array_a = array_a.astype('float64')
print(f"array como float: \n {array_a}")
print("Datatype:", array_a.dtype)

# convert array to list
lis = array_a.tolist()
print("\nList:", lis)
print(type(lis))

array_a:
 [[ 1.  2.  3.  4.]
 [ 2.  3.  4. nan]] 

Size: 8
len: 2
Shape: (2, 4)
Matriz traspuesta:
 [[ 1.  2.]
 [ 2.  3.]
 [ 3.  4.]
 [ 4. nan]]
Shape de la matriz traspuesta: (4, 2)
Cambiamos las dimensiones a (1,8): [[ 1.  2.  3.  4.  2.  3.  4. nan]]
Datatype: float64
array como float: 
 [[ 1.  2.  3.  4.]
 [ 2.  3.  4. nan]]
Datatype: float64

List: [[1.0, 2.0, 3.0, 4.0], [2.0, 3.0, 4.0, nan]]
<class 'list'>


In [10]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f"Array : \n{arr}\n")

print(f"Array tras borrar elementos: \n{np.delete(arr, 1, axis = 1)}")
print(f"Array tras insertar elementos: \n{np.insert(arr, 1, 6, axis = 0)}")
print(f"Array tras añadir elementos al final: \n{np.append(arr, [[6,6,6,6]], axis = 0)}")


## Ejercicio: Usar append para añadir una columna al final



Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array tras borrar elementos: 
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]
Array tras insertar elementos: 
[[ 1  2  3  4]
 [ 6  6  6  6]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array tras añadir elementos al final: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 6  6  6  6]]


In [11]:
# ARRAYS: FILTRAR DATOS ---

array_a = np.array([1, 4, 2, 3])
print(f"Array:\n {array_a}")

array_a.sort()
print(f"Array ordenado de menor a mayor:\n {array_a}")

print(f"¿Los valores son mayores que 2?:\n {array_a > 2}")

print(f"Filtrar elementos mayores que 2:\n {array_a[array_a > 2]}")
print(f"Filtrar elementos mayores que 2 y menores que 4:\n {array_a[(array_a > 2) & (array_a < 4)]}")


Array:
 [1 4 2 3]
Array ordenado de menor a mayor:
 [1 2 3 4]
¿Los valores son mayores que 2?:
 [False False  True  True]
Filtrar elementos mayores que 2:
 [3 4]
Filtrar elementos mayores que 2 y menores que 4:
 [3]


In [12]:
# MATRICES: FILTRAR DATOS ---

lista_de_listas=[ [1  ,-4],
                  [12 , 3],
                  [7.2, 5]]

a = np.array(lista_de_listas)

print(f"array:\n{a}\n")

print(f"Elementos individuales: \nElemento (0,1): {a[0,1]} \nElemento (2,1): {a[2,1]}\n")

print(f"Vector de elementos de la fila 1: \n{a[1,:]}\n")

print(f"Vector de elementos de la columna 0: \n{a[:,0]}\n")

print(f"Submatriz de 2x2 con las primeras dos filas: \n{a[0:2,:]}\n")

array:
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]

Elementos individuales: 
Elemento (0,1): -4.0 
Elemento (2,1): 5.0

Vector de elementos de la fila 1: 
[12.  3.]

Vector de elementos de la columna 0: 
[ 1.  12.   7.2]

Submatriz de 2x2 con las primeras dos filas: 
[[ 1. -4.]
 [12.  3.]]



### Números aleatorios

Los números aleatorios son aquellos que no siguen un patrón predecible. Imagina lanzar un dado: cada vez que lo lanzas, el resultado es un número aleatorio entre 1 y 6, ya que no puedes predecir cuál saldrá. En programación, necesitamos generar números aleatorios para cosas como:

- Simulaciones.
- Modelos estadísticos.
- Pruebas y experimentos controlados.

Es aqui donde numpy nos puede ayudar, ya que tiene un módulo llamado __numpy.random__, que nos permite generar números aleatorios de diferentes formas. Esto es muy útil si queremos hacer simulaciones o crear datos ficticios para probar cosas.

In [13]:
print(f"Creacion de array con random.rand (valores aleatorios entre 0 y 1): {np.random.rand(5)}")


Creacion de array con random.rand (valores aleatorios entre 0 y 1): [0.70602063 0.27012731 0.06128212 0.81147926 0.49341054]


Con esto somos capaces de generar números aleatorios, pero en ocasiones queremos generar números aleatorios con ciertos requisitos o restricciones. Para eso el modulo random tiene una serie de funciones para que usemosla que más nos interese.

In [14]:
# Genera un número entero aleatorio entre 1 y 6 (como un dado)
numero_dado = np.random.randint(low = 1, high = 7, size = 1)
print(f"Cara del dado: {numero_dado}")

Cara del dado: [3]


In [15]:
# Genera 10 números aleatorios con distribución normal (media=0, desviación estándar=1)
numeros_normales = np.random.normal(loc = 0, scale = 1, size=10)
print(f"Numeros normales:\n {numeros_normales}\n")


# Genera un números aleatorio con distribución binomial (n_observaciones=10, probbilidad de exito=0.5)
numeros_binomiales = np.random.binomial(n = 10, p = 0.5, size=10)
print(f"Numeros binomiales:\n {numeros_binomiales}")

Numeros normales:
 [-1.08227005 -0.44135147  0.91556503 -1.50932808 -1.29413756  0.82111126
  0.98640228  1.05987643  0.65197583 -1.0025265 ]

Numeros binomiales:
 [8 4 7 6 5 5 5 6 7 5]


In [ ]:
## Ejercicio:
## Dada una serie de alumnos, vamos a obtener una ordenación aleatoria

# Lista de 10 alumnos
alumnos = ['Alumno1', 'Alumno2', 'Alumno3', 'Alumno4', 'Alumno5',
           'Alumno6', 'Alumno7', 'Alumno8', 'Alumno9', 'Alumno10']


['Alumno1', 'Alumno4', 'Alumno8', 'Alumno2', 'Alumno3', 'Alumno5', 'Alumno10', 'Alumno7', 'Alumno9', 'Alumno6']


array(['Alumno2', 'Alumno7', 'Alumno6', 'Alumno10', 'Alumno9', 'Alumno5',
       'Alumno8', 'Alumno4', 'Alumno1', 'Alumno3'], dtype='<U8')

In [ ]:
## Solucion:

# Lista para almacenar el resultado de la selección aleatoria
alumnos_seleccionados = []

# Selección aleatoria de alumnos usando random.randint
while len(alumnos_seleccionados) < len(alumnos):
    # Genera un índice aleatorio entre 0 y el número de alumnos - 1
    indice_aleatorio = np.random.randint(0, len(alumnos))

    # Si el alumno no ha sido seleccionado antes, lo añadimos a la lista
    if alumnos[indice_aleatorio] not in alumnos_seleccionados:
        alumnos_seleccionados.append(alumnos[indice_aleatorio])

# Imprimimos la lista de alumnos seleccionados aleatoriamente
print(alumnos_seleccionados)



#np.random.permutation(alumnos) #? Ordernar usando permutaciones


In [ ]:

# Lista de 10 alumnos
alumnos = ['Alumno1', 'Alumno2', 'Alumno3', 'Alumno4', 'Alumno5',
           'Alumno6', 'Alumno7', 'Alumno8', 'Alumno9', 'Alumno10']

# Número de alumnos
n_alumnos = len(alumnos)

# Genera una lista de índices aleatorios sin repetir usando np.random.choice
indices_aleatorios = np.random.choice(n_alumnos, size=2, replace=False)

# Selecciona a los alumnos basándote en los índices aleatorios generados
alumnos_seleccionados = [alumnos[i] for i in indices_aleatorios]

# Imprimir la lista de alumnos seleccionados aleatoriamente
print(alumnos_seleccionados)

['Alumno9', 'Alumno3']


In [ ]:
# np.random.seed(42)  #? Si queremos reproducibilidad, necesitamos una semilla

alumnos = ['Alumno1', 'Alumno2', 'Alumno3', 'Alumno4', 'Alumno5',
           'Alumno6', 'Alumno7', 'Alumno8', 'Alumno9', 'Alumno10']

alumnos_aleatorios = np.random.permutation(alumnos)

print(alumnos_aleatorios)

['Alumno9' 'Alumno2' 'Alumno6' 'Alumno1' 'Alumno8' 'Alumno3' 'Alumno10'
 'Alumno5' 'Alumno4' 'Alumno7']


### ¿Por qué es útil esto?

- Simulaciones: Imagina que estás simulando el lanzamiento de un dado 100 veces. Puedes usar np.random.randint() para simularlo rápidamente.

- Generación de datos ficticios: Si necesitas crear datos para practicar o probar un modelo, Numpy facilita la generación de números aleatorios que siguen patrones específicos (distribución normal, uniforme, etc.).

- Pruebas y experimentos: En muchos experimentos, es útil generar datos aleatorios para probar hipótesis o ver cómo un sistema responde a entradas no predecibles.

Numpy no solo genera números aleatorios, sino que te permite hacerlo de forma eficiente y en diferentes formas (arrays, matrices, distribuciones específicas). Esto es increíblemente útil cuando trabajamos con datos o simulaciones.

### Funciones estadisticas

Numpy nos permite calcular estadísticas sobre uestros datos, lo cual es útil para poder tener un mejor entendimiento de estos. A continuación veremos las más conocidas.

In [ ]:
datos = np.random.normal(40, 10, 100)

print(f"Datos:\n{datos}\n")
print(f"Media de los datos: {np.mean(datos)}")
print(f"Suma de los datos: {np.sum(datos)}")
print(f"Minimo valor de los datos: {np.min(datos)}")
print(f"Maximo valor de los datos: {np.max(datos)}")
print(f"Mediana de los datos: {np.median(datos)}")
print(f"Percentil 75 de los datos: {np.percentile(datos, 75)}")
print(f"Desviacion estandard de los datos: {np.std(datos)}")

Datos:
[55.89838978 45.74071221 53.99594645 26.57872252 26.34175845 38.5103069
 45.02784427 57.96360823 47.06078914 37.57318723 29.73630792 52.30000573
 30.35294574 56.28468555 37.1561535  55.90582073 46.7893129  38.63004511
 34.80603628 36.59092123 44.28316692 40.77156496 34.06188592 38.3436859
 40.7857703  18.71265906 44.58168115 30.20278775 28.46667597 23.12655653
 22.06107502 26.44552497 32.90979042 59.53259138 34.74120324 41.77750106
 44.00481387 41.31065186 39.22556539 28.04706236 54.50927548 58.07196644
 23.17341306 29.75971409 37.20189658 30.35462205 45.05965553 32.71727798
 61.65056068 51.90548594 42.12574031 50.26986263 51.05900424 34.36052512
 31.83782755 40.78143063 48.61636124 41.39060399 24.23003518 31.97175556
 39.26027136 39.24334396 59.72542177 26.14012058 45.05589242 54.89113108
 62.71449745 35.95602577 44.91429453 45.69760357 41.95481732 39.01154799
 44.3597539  14.67753915 46.8206949  41.26177904 37.77525103 60.46862196
 33.25065981 35.96924011 59.91553302 31.679386

In [ ]:
datos = np.array([[1,2,3],[4,5,6]])

print(f"Datos:\n{datos}\n")
print(f"Media de los datos: {np.mean(datos)}")
print(f"Suma de los datos: {np.sum(datos)}")
print(f"Minimo valor de los datos: {np.min(datos)}")
print(f"Maximo valor de los datos: {np.max(datos)}")
print(f"Mediana de los datos: {np.median(datos)}")
print(f"Percentil 75 de los datos: {np.percentile(datos, 75)}")
print(f"Desviacion estandard de los datos: {np.std(datos)}")

Datos:
[[1 2 3]
 [4 5 6]]

Media de los datos: 3.5
Suma de los datos: 21
Minimo valor de los datos: 1
Maximo valor de los datos: 6
Mediana de los datos: 3.5
Percentil 75 de los datos: 4.75
Desviacion estandard de los datos: 1.707825127659933


In [16]:
# Vamos a complicar esto un poco añadiendo valores nulos.
# Veremos un ejemplo calculando el maximo


datos = np.array([[1,2,3],[4,5,np.nan]])

print(f"Datos:\n{datos}\n")

print(f"Maximo valor de los datos: {np.max(datos, where = ~np.isnan(datos), initial=-np.inf)}")
print(f"Maximo valor de los datos: {np.nanmax(datos)}")
print(f"Maximo valor de los datos: {np.max(datos[~np.isnan(datos)])}") #! Esta forma fallara si queremos hacer los calculos en un eje

Datos:
[[ 1.  2.  3.]
 [ 4.  5. nan]]

Maximo valor de los datos: 5.0
Maximo valor de los datos: 5.0
Maximo valor de los datos: 5.0
