# Numpy

NumPy es el paquete fundamental para la computación científica en Python. Es una librería de Python que proporciona un objeto array multidimensional,  y una serie de rutinas para operaciones rápidas sobre arrays, incluyendo operaciones matemáticas, lógicas, manipulación de formas, ordenación, selección, álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.

Existen varias diferencias importantes entre los arrays de NumPy y las listas estándar de Python:

- Los arrays de NumPy tienen un tamaño fijo en el momento de su creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Si se cambia el tamaño de una matriz NumPy, se creará un nuevo array y se borrará el original.

- Los elementos de un array de NumPy deben ser todos del mismo tipo de datos y, por tanto, tendrán el mismo tamaño en memoria.

- Los arrays de NumPy facilitan las operaciones matemáticas avanzadas y otros tipos de operaciones con grandes cantidades de datos. Normalmente, estas operaciones se ejecutan de forma más eficiente y con menos código que con las listas incorporadas en Python.

- Una bateria creciente de paquetes científicos y matemáticos basados en Python utilizan arrays de NumPy; aunque normalmente admiten la entrada de listas de Python, convierten dicha entrada en arrays de NumPy antes de procesarla, y a menudo dan como salida arrays de NumPy. En otras palabras, para utilizar eficientemente gran parte del software científico/matemático actual basado en Python, no basta con saber utilizar listas, sino que también hay que saber utilizar los arrays de NumPy.

- Un array puede ser de una dimensión (como una lista), de dos dimensiones (como una matriz) o incluso de más dimensiones.


![arrays de distintas dimensiones](https://www.pythontutorial.net/wp-content/uploads/2022/08/what-is-numpy-1024x572.png)

### Creación de arrays

In [31]:
import numpy as np


In [32]:
# ARRAYS: FORMAS DE CREACION ---

print(f"Creacion de array con lista (se especifican los valores): {np.array([1,2,3])}")

print(f"Creacion de array con arange (valores spaciados en un intervalo): {np.arange(start = 1, stop = 10, step = 1)}")

print(f"Creacion de array con linspace (valores espaciados en un intervalo): {np.linspace(start = 1, stop = 10, num = 5)}")

print(f"Creacion de array con zeros (todos los valores son 0): {np.zeros(shape = 5, dtype=int)}")

print(f"Creacion de array con zeros (todos los valores son 0): {np.zeros(shape = (4,4), dtype=int)}")

print(f"Creacion de array con ones (todos los valores son 1): {np.ones(5, dtype=int)}")



Creacion de array con lista (se especifican los valores): [1 2 3]
Creacion de array con arange (valores spaciados en un intervalo): [1 2 3 4 5 6 7 8 9]
Creacion de array con linspace (valores espaciados en un intervalo): [ 1.    3.25  5.5   7.75 10.  ]
Creacion de array con zeros (todos los valores son 0): [0 0 0 0 0]
Creacion de array con zeros (todos los valores son 0): [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Creacion de array con ones (todos los valores son 1): [1 1 1 1 1]


In [33]:
# MATRICES: ---
lista_a = [1, 2]
lista_b = [4, 5]

matriz_a_con_listas = [lista_a, lista_a]
matriz_b_con_listas = [lista_b, lista_b]

matriz_a_con_arrays = np.array([lista_a, lista_a])
matriz_b_con_arrays = np.array([lista_b, lista_b])

print(f"Así se vería la matriz_a en listas: \n {matriz_a_con_listas}")
print(f"Así se vería la matriz_b en listas: \n {matriz_b_con_listas}")

print(f"Así se vería la matriz_a en numpy: \n {matriz_a_con_arrays}")
print(f"Así se vería la matriz_b en numpy: \n {matriz_b_con_arrays}")

Así se vería la matriz_a en listas: 
 [[1, 2], [1, 2]]
Así se vería la matriz_b en listas: 
 [[4, 5], [4, 5]]
Así se vería la matriz_a en numpy: 
 [[1 2]
 [1 2]]
Así se vería la matriz_b en numpy: 
 [[4 5]
 [4 5]]


### Operaciones con arrays

In [34]:
# ARRAYS: OPERACION SUMA ----
lista_a = [1, 2]
lista_b = [4, 5]

array_a = np.array(lista_a)
array_b = np.array(lista_b)

print(f"Sumamos las listas: {lista_a + lista_b}")
print(f"Sumamos los arrays: {array_a + array_b}")

# Si quiero que las listas se sumen como los arrays
print(f"Sumando las listas como si fuesen arrays: {[a + b for a, b in zip(lista_a, lista_b)]}")

# Si quiero que los arrays se sumen como las listas
print(f"Si queremos concatenar los arrays como las listas: {np.concatenate((array_a, array_b))}")

Sumamos las listas: [1, 2, 4, 5]
Sumamos los arrays: [5 7]
Sumando las listas como si fuesen arrays: [5, 7]
Si queremos concatenar los arrays como las listas: [1 2 4 5]


In [35]:
# ARRAYS: OPERACION MULTIPLICACION ---


# print(f"Multiplicamos las listas: {lista_a * lista_b}")  #! Esto dara error ya que no se pueden multiplicar listas por defecto

print(f"Multiplicamos los arrays: {array_a * array_b}")
print(f"Multiplicamos las listas como si fuesen arrays: {[a * b for a, b in zip(lista_a, lista_b)]}")


Multiplicamos los arrays: [ 4 10]
Multiplicamos las listas como si fuesen arrays: [4, 10]


In [36]:
# MATRICES: OPERACION MULTIPLICACION ---

resultado_con_arrays = matriz_a_con_arrays * matriz_b_con_arrays
print(f"Así se vería la multiplicacion usando arrays: \n {resultado_con_arrays}")


resultado_con_listas = [[0 for _ in range(len(matriz_b_con_listas[0]))] for _ in range(len(matriz_a_con_listas))]
for i in range(len(matriz_a_con_listas)):  # Filas de matriz_a
  for j in range(len(matriz_b_con_listas[0])):
    resultado_con_listas[i][j] = matriz_a_con_listas[i][j] * matriz_b_con_listas[i][j]

print(f"Así se vería la multiplicacion usando listas: \n {resultado_con_listas}")



Así se vería la multiplicacion usando arrays: 
 [[ 4 10]
 [ 4 10]]
Así se vería la multiplicacion usando listas: 
 [[4, 10], [4, 10]]


In [37]:
# MATRICES: OPERACION MULTIPLICACION DOT ---

print(f"Multiplicamos matriz_a_con_arrays con matriz_b_con_arrays:\n {np.dot(matriz_a_con_arrays, matriz_b_con_arrays)}")
print(f"Multiplicamos matriz_b_con_arrays con matriz_a_con_arrays:\n {np.dot(matriz_b_con_arrays, matriz_a_con_arrays)}")



Multiplicamos matriz_a_con_arrays con matriz_b_con_arrays:
 [[12 15]
 [12 15]]
Multiplicamos matriz_b_con_arrays con matriz_a_con_arrays:
 [[ 9 18]
 [ 9 18]]


In [38]:
# MATRICES: OPERACIONES GENERICAS ---

print(f"Sumamos 10 a todos los elementos de la matriz:\n {matriz_a_con_arrays + 10}")
print(f"Multiplicamos por 10 todos los elementos de la matriz:\n {matriz_a_con_arrays * 10}")
print(f"Calculamos la raiz cuadrada de todos los elementos de la matriz:\n {np.sqrt(matriz_a_con_arrays)}")
print(f"Calculamos el logaritmo de todos los elementos de la matriz:\n {np.log(matriz_a_con_arrays)}")
print(f"Calculamos el seno de todos los elementos de la matriz:\n {np.sin(matriz_a_con_arrays)}")


Sumamos 10 a todos los elementos de la matriz:
 [[11 12]
 [11 12]]
Multiplicamos por 10 todos los elementos de la matriz:
 [[10 20]
 [10 20]]
Calculamos la raiz cuadrada de todos los elementos de la matriz:
 [[1.         1.41421356]
 [1.         1.41421356]]
Calculamos el logaritmo de todos los elementos de la matriz:
 [[0.         0.69314718]
 [0.         0.69314718]]
Calculamos el seno de todos los elementos de la matriz:
 [[0.84147098 0.90929743]
 [0.84147098 0.90929743]]


### Propiedades

In [39]:
# ARRAYS: PROPIEDADES ---

array_a = np.array([[1, 2, 3, 4], [2,3,4,np.nan]]) #np.nan o np.na depende de la libreria

print(f"array_a:\n {array_a} \n")

print("Size:", array_a.size)

# check len of the array
print("len:", len(array_a))

# check shape of the array
print("Shape:", array_a.shape)

print(f"Matriz traspuesta:\n {array_a.T}")

print(f"Shape de la matriz traspuesta: {array_a.T.shape}")

print(f"Cambiamos las dimensiones a (1,8): {array_a.reshape(1, 8)}")

# check dtype of the array elements
print("Datatype:", array_a.dtype)

# change the dtype to 'float64'
array_a = array_a.astype('float64')
print(f"array como float: \n {array_a}")
print("Datatype:", array_a.dtype)

# convert array to list
lis = array_a.tolist()
print("\nList:", lis)
print(type(lis))

array_a:
 [[ 1.  2.  3.  4.]
 [ 2.  3.  4. nan]] 

Size: 8
len: 2
Shape: (2, 4)
Matriz traspuesta:
 [[ 1.  2.]
 [ 2.  3.]
 [ 3.  4.]
 [ 4. nan]]
Shape de la matriz traspuesta: (4, 2)
Cambiamos las dimensiones a (1,8): [[ 1.  2.  3.  4.  2.  3.  4. nan]]
Datatype: float64
array como float: 
 [[ 1.  2.  3.  4.]
 [ 2.  3.  4. nan]]
Datatype: float64

List: [[1.0, 2.0, 3.0, 4.0], [2.0, 3.0, 4.0, nan]]
<class 'list'>


In [40]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f"Array : \n{arr}\n")

print(f"Array tras borrar elementos: \n{np.delete(arr, 1, axis = 1)}")
print(f"Array tras insertar elementos: \n{np.insert(arr, 1, 6, axis = 0)}")
print(f"Array tras añadir elementos al final: \n{np.append(arr, [[6,6,6,6]], axis = 0)}") #axis 1 no funciona, pues inserta
# print(f"Array tras añadir elementos a la derecha: \n{np.append(arr, [[6,6,6,6]], axis = 1)}") #axis 1 no funciona, pues inserta

## Ejercicio: Usar append para añadir una columna al final



Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array tras borrar elementos: 
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]
Array tras insertar elementos: 
[[ 1  2  3  4]
 [ 6  6  6  6]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array tras añadir elementos al final: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 6  6  6  6]]


In [41]:
# ARRAYS: FILTRAR DATOS ---

array_a = np.array([1, 4, 2, 3])
print(f"Array:\n {array_a}")

array_a.sort()
print(f"Array ordenado de menor a mayor:\n {array_a}")

print(f"¿Los valores son mayores que 2?:\n {array_a > 2}")

print(f"Filtrar elementos mayores que 2:\n {array_a[array_a > 2]}")
print(f"Filtrar elementos mayores que 2 y menores que 4:\n {array_a[(array_a > 2) & (array_a < 4)]}")


Array:
 [1 4 2 3]
Array ordenado de menor a mayor:
 [1 2 3 4]
¿Los valores son mayores que 2?:
 [False False  True  True]
Filtrar elementos mayores que 2:
 [3 4]
Filtrar elementos mayores que 2 y menores que 4:
 [3]


In [42]:
# MATRICES: FILTRAR DATOS ---

lista_de_listas=[ [1  ,-4],
                  [12 , 3],
                  [7.2, 5]]

a = np.array(lista_de_listas)

print(f"array:\n{a}\n")

print(f"Elementos individuales: \nElemento (0,1): {a[0,1]} \nElemento (2,1): {a[2,1]}\n")

print(f"Vector de elementos de la fila 1: \n{a[1,:]}\n")

print(f"Vector de elementos de la columna 0: \n{a[:,0]}\n")

print(f"Submatriz de 2x2 con las primeras dos filas: \n{a[0:2,:]}\n")

array:
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]

Elementos individuales: 
Elemento (0,1): -4.0 
Elemento (2,1): 5.0

Vector de elementos de la fila 1: 
[12.  3.]

Vector de elementos de la columna 0: 
[ 1.  12.   7.2]

Submatriz de 2x2 con las primeras dos filas: 
[[ 1. -4.]
 [12.  3.]]



### Números aleatorios

Los números aleatorios son aquellos que no siguen un patrón predecible. Imagina lanzar un dado: cada vez que lo lanzas, el resultado es un número aleatorio entre 1 y 6, ya que no puedes predecir cuál saldrá. En programación, necesitamos generar números aleatorios para cosas como:

- Simulaciones.
- Modelos estadísticos.
- Pruebas y experimentos controlados.

Es aqui donde numpy nos puede ayudar, ya que tiene un módulo llamado __numpy.random__, que nos permite generar números aleatorios de diferentes formas. Esto es muy útil si queremos hacer simulaciones o crear datos ficticios para probar cosas.

In [43]:
print(f"Creacion de array con random.rand (valores aleatorios entre 0 y 1): {np.random.rand(5)}")


Creacion de array con random.rand (valores aleatorios entre 0 y 1): [0.40915557 0.86639989 0.80270269 0.3978329  0.68161845]


Con esto somos capaces de generar números aleatorios, pero en ocasiones queremos generar números aleatorios con ciertos requisitos o restricciones. Para eso el modulo random tiene una serie de funciones para que usemosla que más nos interese.

In [44]:
# Genera un número entero aleatorio entre 1 y 6 (como un dado)
numero_dado = np.random.randint(low = 1, high = 7, size = 1)
print(f"Cara del dado: {numero_dado}")

Cara del dado: [6]


In [45]:
# Genera 10 números aleatorios con distribución normal (media=0, desviación estándar=1)
numeros_normales = np.random.normal(loc = 0, scale = 1, size=10)
print(f"Numeros normales:\n {numeros_normales}\n")


# Genera un números aleatorio con distribución binomial (n_observaciones=10, probbilidad de exito=0.5)
numeros_binomiales = np.random.binomial(n = 10, p = 0.5, size=10)
print(f"Numeros binomiales:\n {numeros_binomiales}")

Numeros normales:
 [-1.80105584 -1.25821303 -0.72793428 -0.23232401 -1.57322004 -0.27289106
  1.32806704 -0.96187018  0.06791599 -0.62593568]

Numeros binomiales:
 [6 6 5 6 5 6 3 7 4 2]


In [46]:
## Ejercicio:
## Dada una serie de alumnos, vamos a obtener una ordenación aleatoria

# Lista de 10 alumnos
alumnos = ['Alumno1', 'Alumno2', 'Alumno3', 'Alumno4', 'Alumno5',
           'Alumno6', 'Alumno7', 'Alumno8', 'Alumno9', 'Alumno10']


In [47]:
array_alumnos = np.array(alumnos)

array_alumnos = np.random.permutation(array_alumnos)
print(array_alumnos)

['Alumno6' 'Alumno4' 'Alumno3' 'Alumno5' 'Alumno1' 'Alumno2' 'Alumno8'
 'Alumno7' 'Alumno9' 'Alumno10']


In [48]:
## Solucion:

# Lista para almacenar el resultado de la selección aleatoria
alumnos_seleccionados = []

# Selección aleatoria de alumnos usando random.randint
while len(alumnos_seleccionados) < len(alumnos):
    # Genera un índice aleatorio entre 0 y el número de alumnos - 1
    indice_aleatorio = np.random.randint(0, len(alumnos))

    # Si el alumno no ha sido seleccionado antes, lo añadimos a la lista
    if alumnos[indice_aleatorio] not in alumnos_seleccionados:
        alumnos_seleccionados.append(alumnos[indice_aleatorio])

# Imprimimos la lista de alumnos seleccionados aleatoriamente
print(alumnos_seleccionados)

np.random.permutation(alumnos_seleccionados) #? Ordernar usando permutaciones


['Alumno6', 'Alumno2', 'Alumno10', 'Alumno4', 'Alumno3', 'Alumno5', 'Alumno1', 'Alumno9', 'Alumno8', 'Alumno7']


array(['Alumno4', 'Alumno5', 'Alumno10', 'Alumno1', 'Alumno2', 'Alumno9',
       'Alumno3', 'Alumno6', 'Alumno8', 'Alumno7'], dtype='<U8')

In [49]:

# Lista de 10 alumnos
alumnos = ['Alumno1', 'Alumno2', 'Alumno3', 'Alumno4', 'Alumno5',
           'Alumno6', 'Alumno7', 'Alumno8', 'Alumno9', 'Alumno10']

# Número de alumnos
n_alumnos = len(alumnos)

# Genera una lista de índices aleatorios sin repetir usando np.random.choice
indices_aleatorios = np.random.choice(n_alumnos, size=2, replace=False)

# Selecciona a los alumnos basándote en los índices aleatorios generados
alumnos_seleccionados = [alumnos[i] for i in indices_aleatorios]

# Imprimir la lista de alumnos seleccionados aleatoriamente
print(alumnos_seleccionados)

['Alumno1', 'Alumno8']


In [50]:
# np.random.seed(42)  #? Si queremos reproducibilidad, necesitamos una semilla

alumnos = ['Alumno1', 'Alumno2', 'Alumno3', 'Alumno4', 'Alumno5',
           'Alumno6', 'Alumno7', 'Alumno8', 'Alumno9', 'Alumno10']

alumnos_aleatorios = np.random.permutation(alumnos)

print(alumnos_aleatorios)

['Alumno7' 'Alumno2' 'Alumno9' 'Alumno10' 'Alumno8' 'Alumno3' 'Alumno5'
 'Alumno1' 'Alumno4' 'Alumno6']


### ¿Por qué es útil esto?

- Simulaciones: Imagina que estás simulando el lanzamiento de un dado 100 veces. Puedes usar np.random.randint() para simularlo rápidamente.

- Generación de datos ficticios: Si necesitas crear datos para practicar o probar un modelo, Numpy facilita la generación de números aleatorios que siguen patrones específicos (distribución normal, uniforme, etc.).

- Pruebas y experimentos: En muchos experimentos, es útil generar datos aleatorios para probar hipótesis o ver cómo un sistema responde a entradas no predecibles.

Numpy no solo genera números aleatorios, sino que te permite hacerlo de forma eficiente y en diferentes formas (arrays, matrices, distribuciones específicas). Esto es increíblemente útil cuando trabajamos con datos o simulaciones.

### Funciones estadisticas

Numpy nos permite calcular estadísticas sobre uestros datos, lo cual es útil para poder tener un mejor entendimiento de estos. A continuación veremos las más conocidas.

In [51]:
datos = np.random.normal(40, 10, 100)

print(f"Datos:\n{datos}\n")
print(f"Media de los datos: {np.mean(datos)}")
print(f"Suma de los datos: {np.sum(datos)}")
print(f"Minimo valor de los datos: {np.min(datos)}")
print(f"Maximo valor de los datos: {np.max(datos)}")
print(f"Mediana de los datos: {np.median(datos)}")
print(f"Percentil 75 de los datos: {np.percentile(datos, 75)}")
print(f"Desviacion estandard de los datos: {np.std(datos)}")

Datos:
[18.64332523 31.15718408 41.98491146 33.72667186 34.23920679 30.97172436
 42.79201141 43.41838211 26.46734155 43.15106949 48.75315024 37.80855269
 24.1893903  52.70882048 36.1727253  24.91155196 43.48317076 31.9945204
 40.24292525 60.77347343 32.98348657 22.04574191 38.45005072 37.67810662
 30.24689672 41.56428106 22.81196542 45.50683152 27.41698088 32.55782148
 13.39747074 38.84029384 44.82100048 39.33851482 35.16553746 21.97142663
 28.38432734 30.10266611 50.44782134 52.84015043 38.88023312 29.37227779
 36.46440532 39.85774423 28.9451468  56.80980154 38.9832294  47.72868635
 40.29004676 39.24989954 32.44062897 34.98274103 62.49885576 44.83357027
 37.65064353 30.79018084 46.52686937 46.26477355 33.90063402 50.42109084
 49.34284393 46.38398272 51.26444605 44.19114683 23.16217848 43.77440151
 43.02514147 51.02116589 33.52130449 45.76253743 33.51890315 34.06571285
 29.42640914 23.43632716 48.98044839 33.78189859 46.80541787 37.31370084
 45.33953136 39.53367164 34.19243979 43.47037

In [52]:
datos = np.array([[1,2,3],[4,5,6]])

print(f"Datos:\n{datos}\n")
print(f"Media de los datos: {np.mean(datos)}")
print(f"Suma de los datos: {np.sum(datos)}")
print(f"Minimo valor de los datos: {np.min(datos)}")
print(f"Maximo valor de los datos: {np.max(datos)}")
print(f"Mediana de los datos: {np.median(datos)}")
print(f"Percentil 75 de los datos: {np.percentile(datos, 75)}")
print(f"Desviacion estandard de los datos: {np.std(datos)}")

Datos:
[[1 2 3]
 [4 5 6]]

Media de los datos: 3.5
Suma de los datos: 21
Minimo valor de los datos: 1
Maximo valor de los datos: 6
Mediana de los datos: 3.5
Percentil 75 de los datos: 4.75
Desviacion estandard de los datos: 1.707825127659933


In [53]:
# Vamos a complicar esto un poco añadiendo valores nulos.
# Veremos un ejemplo calculando el maximo


datos = np.array([[1,2,3],[4,5,np.nan]])

print(f"Datos:\n{datos}\n")

print(f"Maximo valor de los datos: {np.max(datos, where = ~np.isnan(datos), initial=-np.inf)}") # virgulilla es lo contrario, se busca donde los datos no son nulos, y empieza por - infinito
print(f"Maximo valor de los datos: {np.nanmax(datos)}")
print(f"Maximo valor de los datos: {np.max(datos[~np.isnan(datos)])}") #! Esta forma fallara si queremos hacer los calculos en un eje

Datos:
[[ 1.  2.  3.]
 [ 4.  5. nan]]

Maximo valor de los datos: 5.0
Maximo valor de los datos: 5.0
Maximo valor de los datos: 5.0


In [55]:
array = np.random.randint(low = 1, high = 7, size = (2,100000)).sum(axis = 0)
np.unique(array, return_counts=True)

probabilidad = np.unique(array, return_counts=True)[1] / len(array)

print(f'La probabilidad de obtener cada suma es: {probabilidad*100}%, siendo 2 la minima y 12 la maxima')


La probabilidad de obtener cada suma es: [ 2.881  5.551  8.344 11.013 13.695 16.808 13.684 11.233  8.438  5.569
  2.784]%, siendo 2 la minima y 12 la maxima


In [56]:
import numpy as np

def calcular_probabilidades_dados(num_tiradas=1000000):

    # Simular el lanzamiento de dos dados num_tiradas veces
    tiradas = np.random.randint(1, 7, size=(num_tiradas, 2))
    suma_tiradas = tiradas.sum(axis=1)

    # Calcular la probabilidad de cada suma
    valores_unicos, conteos = np.unique(suma_tiradas, return_counts=True)
    probabilidades = conteos / num_tiradas
    distribucion_probabilidades = dict(zip(valores_unicos, probabilidades))
    
    # Mostrar las probabilidades para cada suma
    for valor_suma, probabilidad in distribucion_probabilidades.items():
        print(f"Suma {valor_suma}: {probabilidad:.2%} de probabilidad")

if __name__ == "__main__":
    calcular_probabilidades_dados()


Suma 2: 2.81% de probabilidad
Suma 3: 5.57% de probabilidad
Suma 4: 8.29% de probabilidad
Suma 5: 11.06% de probabilidad
Suma 6: 13.89% de probabilidad
Suma 7: 16.64% de probabilidad
Suma 8: 13.95% de probabilidad
Suma 9: 11.10% de probabilidad
Suma 10: 8.36% de probabilidad
Suma 11: 5.52% de probabilidad
Suma 12: 2.80% de probabilidad
